---
- name: OpenTelekom ansible task test playbook
  hosts: infra
  roles:
    - { role: dms, tags: [ test-dms, apply ], state='present' }
    - { role: dms, tags: [ test-dms, destroy], state='absent' }
    - { role: vpc, tags: [ test-vpc, apply, test-nat, test-rds, test-css, test-cce ], state='present' }
    - { role: kms, tags: [ test-kms, apply ], state='present' }
    - { role: nat, tags: [ test-nat, apply ], state='present' }
    - { role: nat, tags: [ test-nat, destroy], state='absent' }
    - { role: rds, tags: [ test-rds, apply ], state='present' }
    - { role: rds, tags: [ test-rds, destroy], state='absent' }
    - { role: css, tags: [ test-css, apply ], state='present' }
    - { role: css, tags: [ test-css, destroy], state='absent' }
    - { role: cce, tags: [ test-cce, apply ], state='present' }
    - { role: cce, tags: [ test-cce, destroy], state='absent' }
    - { role: vpc, tags: [ test-vpc, destroy, test-nat, test-rds, test-css, test-cce ], state='absent' }
    #- { role: exceptiontest, tags: [ test-ex, apply ], state='present' }

    