---
  - name: Test_delete VPC network
    otc_vpc:
      state: "absent"
      auth_type: password
      auth:
        "{{ otc_os_auth }}"
      cacert: "{{ otc_cert_file }}"
      name: "{{ net_admin.vpc.name }}"
    register: network_result
